---
abstract: 'Override subroutines in a module for unit testing'
author:
  - 'Current Maintainer: Geoff Franks <gfranks@cpan.org>'
  - 'Original Author: Simon Flack <simonflk _AT_ cpan.org>'
build_requires:
  Test::More: '0.88'
  Test::Warnings: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-MockModule
provides:
  Test::MockModule:
    file: lib/Test/MockModule.pm
    version: v0.171.0
requires:
  Carp: '0'
  SUPER: '0'
  Scalar::Util: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/geofffranks/test-mockmodule/issues
  homepage: https://github.com/geofffranks/test-mockmodule
  license: http://dev.perl.org/licenses/
  repository: git://github.com/geofffranks/test-mockmodule.git
version: v0.171.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
